### ISSUE TITLE
how solve socket issue installation?

### ISSUE THREAD

**Issue by johnfelipe** [MrH0wl/Cloudmare#1]
Downloading/unpacking socket (from -r requirements.txt (line 6))
  Could not find any downloads that satisfy the requirement socket (from -r requirements.txt (line 6))
Cleaning up...
No distributions at all found for socket (from -r requirements.txt (line 6))
Storing debug log for failure in /root/.pip/pip.log

**Comment by MrH0wl** [comment]
My bad, you don't need to install the socket module, coz it's already included in standard library. Just eliminate that line of requirements.txt
