### ISSUE TITLE
There was an error getting results

### ISSUE THREAD

**Issue by VirtualM20** [MrH0wl/Cloudmare#10]
There was an error getting results
Traceback (most recent call last):
  File "Cloudmare.py", line 79, in <module>
    ip_takes = make_list()
  File "Cloudmare.py", line 32, in make_list
    ip_list = subdomain_tracking(domain)
  File "/root/Cloudmare/lib/core/subdomain_finder.py", line 9, in subdomain_tracking
    if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str

**Comment by MrH0wl** [comment]
Hi, thanks for reporting this issue. Check please if your problem is solved in commit 18035fa075766e9380d40effa4e36b275250738b

**Comment by VirtualM20** [comment]
Fixed, the issue can be closed i think, and thx for the fast reaction.

**Comment by MrH0wl** [comment]
You're welcome!
