### ISSUE TITLE
error when running tool

### ISSUE THREAD

**Issue by sh1va73** [MrH0wl/Cloudmare#11]
I get this error when using this tool:

Traceback (most recent call last):
  File "Cloudmare.py", line 79, in <module>
    ip_takes = make_list()
  File "Cloudmare.py", line 32, in make_list
    ip_list = subdomain_tracking(domain)
  File "/opt/Cloudmare/lib/core/subdomain_finder.py", line 8, in subdomain_tracking
    res = DNSDumpsterAPI(False).search(domain)
  File "/opt/Cloudmare/thirdparty/dnsdumpster/DNSDumpsterAPI.py", line 99, in search
    res['dns_records']['dns'] = self.retrieve_results(tables[0])

Please suggest.

**Comment by MrH0wl** [comment]
I need you to provide more information about the error since I cannot determine where the problem may be.

**Comment by sh1va73** [comment]
I run it on latest Kali version on a .network website with Cloudflare. If you need anymore info let me know what you need.

**Comment by MrH0wl** [comment]
I am very sorry to take some time to respond, the work has put pressure on me. I have tried to replicate the error I am presenting, but the program works correctly for me, so I would need the website where you are trying to see what the problems are based on or I could send you the full trace and the commands I used.

**Comment by sh1va73** [comment]
No worries, thanks for your reply. Unfortunately I can not share as it is a client website and the project is closed now. I will keep using this program, and post back when I have new findings.

**Comment by MrH0wl** [comment]
Okay, I got it. Thank you so much for posting
