### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!

### ISSUE THREAD

**Issue by jordantsap** [MrH0wl/Cloudmare#14]
Using it in Parrot OS 4.7
command python Cloudmare.py target.site 

Output:
/usr/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!

**Comment by niicolasalves** [comment]
> Using it in Parrot OS 4.7
> command python Cloudmare.py target.site
> 
> Output:
> /usr/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/**init**.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!

I installed PySocks via Python and solved it.

`pip3 install pysocks --user`
