### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by factuminc** [MrH0wl/Cloudmare#16]
See the tabs/spacing on lines 57-58: https://github.com/MrH0wl/Cloudmare/blob/1e96a3abace58aba1c439cfe3daeb948572f8b51/Cloudmare.py#L57

Output:
I:\Cloudmare>python Cloudmare.py --help
  File "Cloudmare.py", line 58
    ip_takes.extend(CensysIP)
                            ^
TabError: inconsistent use of tabs and spaces in indentation

Obviously, this is an easy fix although I wanted to point out in case anyone else encounters this.

**Comment by factuminc** [comment]
Additional notes: I received this TabError on Windows 10 and I assume that receiving this message could depend on the OS + python config.

**Comment by MrH0wl** [comment]
Hi, sorry for the inconvenience. The error was not your OS's fault, check if the commit 5d7ae230b68451fd1940f12f69fa8e4da9c307c0 fixes it.

**Comment by factuminc** [comment]
Works great. Thanks for the update! I should have mentioned that it worked fine when i fixed the indentation locally.
