### ISSUE TITLE
Problem with search and dont get further. 

### ISSUE THREAD

**Issue by Klapkaak078** [MrH0wl/Cloudmare#2]
Hello there! 

I get this problem, do you know what i am do rong?

Tracking subdomains and MX records...

[*] Subdomains:
   [+] 104.20.196.6 from: www.addmefast.com
[*] MX Records:
   [+] 74.125.193.27 from: 30 alt2.aspmx.l.google.com.
   [+] 64.233.186.27 from: 20 alt1.aspmx.l.google.com.
   [+] 188.138.106.30 from: 200 zebra430.startdedicated.com.
   [+] 173.194.206.26 from: 10 aspmx.l.google.com.

[*]Enumerating misconfigured DNS subdomains:
   [+] 74.125.193.27 from: 30 alt2.aspmx.l.google.com.
   [+] 64.233.186.27 from: 20 alt1.aspmx.l.google.com.
   [+] 188.138.106.30 from: 200 zebra430.startdedicated.com.
   [+] 173.194.206.26 from: 10 aspmx.l.google.com.
Cloudflare IP Catcher (Auto DIG)...

[*] Checking if 74.125.193.26 are similar to addmefast.com
Traceback (most recent call last):
  File "Cloudmare.py", line 227, in <module>
    first_scan()
  File "Cloudmare.py", line 111, in first_scan
    test2 = requests.get('http://' + ns, timeout=config['http_timeout_seconds'])
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='74.125.193.26', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fddfaa20790>, 'Connection to 74.125.193.26 timed out. (connect timeout=3)'))
root@kali:~/Desktop/Cloudmare# 

Greetings Klapkaak078

**Comment by MrH0wl** [comment]
You can not establish the connection with the ip, it may be because the subdomains are not specific to the website, since they are from third parties(and obviously these are not considered as misconfiguration).

**Comment by Klapkaak078** [comment]
may i ask what you mean, that the misconfigurate the webpage? i had the ip from the server first found on censys but they have a new on because its not pinging, anymore and no direct connection, can you tell me specific what i do rong?

**Comment by MrH0wl** [comment]
That's the problem, they solved their misconfigurations, so the ip can not be easily obtained.

**Comment by Klapkaak078** [comment]
Thank, you can close this ticket issue. have a great one!
