### ISSUE TITLE
MrH0wl/Cloudmare#usage

### ISSUE THREAD

**Issue by Losyon** [MrH0wl/Cloudmare#22]
**Merhaba https://github.com/MrH0wl/Cloudmare#usage vermiş olduğunuzu yapıyoruz adım adım ama 

$ python cloudmare.py target.site --subdomain << algılamıyor komut yok diyor rica etsem kodmu değişti değişti ise güncellini paylaşırmısınız**

**Comment by MrH0wl** [comment]
Hi, I'm already updating the code to fix the existing errors and adding new functions for better search results. Thanks for your report

**Comment by Losyon** [comment]
Rica Ederim
