### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'searchG'

### ISSUE THREAD

**Issue by itsethack** [MrH0wl/Cloudmare#24]
Hi,
I got error when run Cloudmare, 
AttributeError: 'Namespace' object has no attribute 'searchG'
![image](https://user-images.githubusercontent.com/65939746/98498105-848a2d00-2278-11eb-83ef-484a1a5f85b5.png)

So, how to resolve it?
Thanks.

**Comment by MrH0wl** [comment]
Hello, sorry for that, they are arguments that will be added in the next update and I forgot to remove in this version.

Check if https://github.com/MrH0wl/Cloudmare/commit/7b1fe6198c514857e3964504278c6789dd68fa0c solves the problem.
