### ISSUE TITLE
ImportError: No module named pip._internal

### ISSUE THREAD

**Issue by phyohan18** [MrH0wl/Cloudmare#25]
Trying to install Cloudmare by typing "python Cloudmare.py -hh"

And like that appear 

Traceback (most recent call last):
  File "Cloudmare.py", line 9, in <module>
    from lib.parse.cmdline import parser_cmd
  File "/home/peter/Cloudmare/lib/parse/cmdline.py", line 9, in <module>
    from lib.parse.settings import PYVERSION
  File "/home/peter/Cloudmare/lib/parse/settings.py", line 12, in <module>
    from pip._internal import main as pip
ImportError: No module named pip._internal

(P.S i'm using Kali Linux Lates Version)

**Comment by MrH0wl** [comment]
python 2 came to the end of its life. So they removed pip from the latest kali only pip3 available but you can manually install pip.
Installing with get-pip.py

Use 'python3 -hh' instead of 'python -hh'

**Comment by tylerjkline** [comment]
> python 2 came to the end of its life. So they removed pip from the latest kali only pip3 available but you can manually install pip.
> Installing with get-pip.py
> 
> Or you can use 'python3 -hh' instead of 'python -hh'

Can confirm using python3 resolves the issue.

**Comment by tylerjkline** [comment]
Solved — #26
