### ISSUE TITLE
[-]Error: Virustotal probably now is blocking our requests

### ISSUE THREAD

**Issue by galaxydata** [MrH0wl/Cloudmare#27]
python Cloudmare.py -u profitserver.ru

  ____ _                 _ __  __
 / ___| | ___  _   _  __| |  \/  | __ _ _ __ ___
| |   | |/ _ \| | | |/ _` | |\/| |/ _` | '__/ _ \
| |___| | (_) | |_| | (_| | |  | | (_| | | |  __/
 \____|_|\___/ \__,_|\__,_|_|  |_|\__,_|_|  \___| [2.0.11.06]
Automatic CloudProxy and Reverse Proxy bypass tool
##################################################

[?]Enumerating subdomains now for profitserver.ru
[-]Error: Virustotal probably now is blocking our requests

**Comment by PatchByte** [comment]
yeah they changed the ip you need now a virustotal api key i am probaly going to implement it!

**Comment by PatchByte** [comment]
hey mate took a look at this: https://github.com/MrH0wl/Cloudmare/pull/31
