### ISSUE TITLE
Does not work for https://fastpeoplesearch.com/

### ISSUE THREAD

**Issue by sharifulgeo** [MrH0wl/Cloudmare#29]
I tried this script for `https://fastpeoplesearch.com/` but it did not work.

**Comment by PatchByte** [comment]
try it --bruter

**Comment by backofficesolucoes** [comment]
![image](https://user-images.githubusercontent.com/58264334/112387733-e18afa80-8cd0-11eb-9c48-f866d2d4811b.png)

need help-me?

**Comment by PatchByte** [comment]
Uhm shit ok I am going to take a look

**Comment by PatchByte** [comment]
I tried this too but it doesnt work, the url has no subdomains!

**Comment by PatchByte** [comment]
https://i.imgur.com/Zk0Jpet.png

oof it has subdomains but all are configured!
