### ISSUE TITLE
Connection cannot be established... Try to put manually a NS

### ISSUE THREAD

**Issue by r3xar** [MrH0wl/Cloudmare#3]
Hey,
This is a great tool! Thanks!
All queries end with a message:
Is this a mistake?
Can you give an example of a query using the NS option?

Tracking subdomains and MX records...

[*] Subdomains:
   [+] 104.18.52.127 from: zalukaj.tv

[*]Enumerating misconfigured DNS subdomains:
Cloudflare IP Catcher (Auto DIG)...

[*] Checking if  are similar to zalukaj.tv
   [-] Connection cannot be established... Try to put manually a NS

**Comment by MrH0wl** [comment]
Hi, thanks for compliment! :D, as I could see, the page you were testing doesn't count with subdomains that don't belong to cloudflare. The "-ns" option works with a server that verifies the domain under cloudflare, for example:

python Cloudmare.py target.com -ns 152.235.50.180

152.235.50.180 could be either the real ip (you can verify whether it's right or not with cloudmare) or a server that's directly associated with the domain under cloudflare.
