### ISSUE TITLE
Ability to skip obvious domains

### ISSUE THREAD

**Issue by Octolus** [MrH0wl/Cloudmare#32]
Ability to skip obvious domains in the brute process, such as "googlemail" and other google, email domains? Maybe we could have a big list of domains that would NOT be the backend.

**Comment by PatchByte** [comment]
thats actually a good idea, i am going to try something... ;D

**Comment by PatchByte** [comment]
Take a look at this -> https://github.com/MrH0wl/Cloudmare/pull/34
