### ISSUE TITLE
Does not work for https://www.truepeoplesearch.com/ 

### ISSUE THREAD

**Issue by sharifulgeo** [MrH0wl/Cloudmare#35]
I tried to find the real domain for https://www.truepeoplesearch.com/ but failed! Is it possible to get the real domain if even all the subdomains are all configured?

**Comment by MrH0wl** [comment]
You could use the advanced commands using “ cloudmare.py -hh”. I recommend using the brute-force command and either Censys or SecurityTrail API (or both).
