### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by paungabriel1** [mrh0wl/Cloudmare#39]
![image](https://user-images.githubusercontent.com/91350962/150494789-46dac8af-bd68-4e75-902a-7cd77464c571.png)
Hey, i have this error after shodan search done

**Comment by paungabriel1** [comment]
![image](https://user-images.githubusercontent.com/91350962/150498541-298b5ce9-efb7-4ec5-9fc8-c949b0fec59f.png)
New error

**Comment by paungabriel1** [comment]
![image](https://user-images.githubusercontent.com/91350962/150533811-73c37c75-eb46-48f4-826d-a3be25b01693.png)
Why only me?(

**Comment by mrh0wl** [comment]
Check out using: https://github.com/mrh0wl/Cloudmare/commit/c40550fce056b26f0f99eb46578e40134b48c927
