### ISSUE TITLE
subbruter command problem

### ISSUE THREAD

**Issue by Phoenix1112** [mrh0wl/Cloudmare#41]
thanks for this project. When I use the ```--subbruter``` parameter as below, I get an error and the program terminates.  Do you need to use wordlist with this parameter?

```
cyberthereaper@root:~/Cloudmare# python3 Cloudmare.py -u example.com --host example.com --bruter --subbruter --random-agent --ignore-redirects -sC -sSh -sSt

  ____ _                 _ __  __
 / ___| | ___  _   _  __| |  \/  | __ _ _ __ ___
| |   | |/ _ \| | | |/ _` | |\/| |/ _` | '__/ _ \
| |___| | (_) | |_| | (_| | |  | | (_| | | |  __/
 \____|_|\___/ \__,_|\__,_|_|  |_|\__,_|_|  \___| [2.1.10.11]
Automatic CloudProxy and Reverse Proxy bypass tool
##################################################

[?]Enumerating subdomains now for target.com
[-]Error: Virustotal probably now is blocking our requests! Or you have not a valid api key!
   [!]Starting bruteforce module now using subbrute..
Traceback (most recent call last):
  File "Cloudmare.py", line 36, in <module>
    subdomain = sublist3r.main(args.domain, args.threads, output, ports=None, silent=False, verbose=args.verbose, enable_bruteforce=args.subbrute, engines=None) if not args.disableSub else []
  File "/root/Cloudmare/lib/tools/sublist3r.py", line 966, in main
    bruteforce_list = subbrute.print_target(parsed_domain.netloc, record_type, subs, resolvers, process_count, output, json_output, search_list, verbose)
  File "/root/Cloudmare/lib/tools/subbrute/subbrute.py", line 411, in print_target
    for result in run(target, record_type, subdomains, resolve_list, process_count):
  File "/root/Cloudmare/lib/tools/subbrute/subbrute.py", line 427, in run
    if (len(resolve_list) / 16) < process_count:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```

**Comment by Theraqa** [comment]
i get same error too :(

**Comment by dansleboby** [comment]
Me to

**Comment by brainless3178** [comment]
you need to add api key from virus total or you can visit whichever site blocking your request just visit site,sign up and get api key and put it in script :)

**Comment by brainless3178** [comment]
> thanks for this project. When I use the `--subbruter` parameter as below, I get an error and the program terminates. Do you need to use wordlist with this parameter?
> 
> ```
> cyberthereaper@root:~/Cloudmare# python3 Cloudmare.py -u example.com --host example.com --bruter --subbruter --random-agent --ignore-redirects -sC -sSh -sSt
> 
>   ____ _                 _ __  __
>  / ___| | ___  _   _  __| |  \/  | __ _ _ __ ___
> | |   | |/ _ \| | | |/ _` | |\/| |/ _` | '__/ _ \
> | |___| | (_) | |_| | (_| | |  | | (_| | | |  __/
>  \____|_|\___/ \__,_|\__,_|_|  |_|\__,_|_|  \___| [2.1.10.11]
> Automatic CloudProxy and Reverse Proxy bypass tool
> ##################################################
> 
> [?]Enumerating subdomains now for target.com
> [-]Error: Virustotal probably now is blocking our requests! Or you have not a valid api key!
>    [!]Starting bruteforce module now using subbrute..
> Traceback (most recent call last):
>   File "Cloudmare.py", line 36, in <module>
>     subdomain = sublist3r.main(args.domain, args.threads, output, ports=None, silent=False, verbose=args.verbose, enable_bruteforce=args.subbrute, engines=None) if not args.disableSub else []
>   File "/root/Cloudmare/lib/tools/sublist3r.py", line 966, in main
>     bruteforce_list = subbrute.print_target(parsed_domain.netloc, record_type, subs, resolvers, process_count, output, json_output, search_list, verbose)
>   File "/root/Cloudmare/lib/tools/subbrute/subbrute.py", line 411, in print_target
>     for result in run(target, record_type, subdomains, resolve_list, process_count):
>   File "/root/Cloudmare/lib/tools/subbrute/subbrute.py", line 427, in run
>     if (len(resolve_list) / 16) < process_count:
> TypeError: '<' not supported between instances of 'float' and 'NoneType'
> ```

you need to add api key from virus total or you can visit **whichever site blocking your request** just visit site,sign up and get api key and put it in script :)

**Comment by mrh0wl** [comment]
I think in the new update, the problem is solved. Check it now!
