### ISSUE TITLE
shit don't work

### ISSUE THREAD

**Issue by Roboxkin** [mrh0wl/Cloudmare#44]
After spending more than five hours, I still haven't installed the lxml library. I don’t know how this is possible, I searched for an answer on Google, reinstalled python 3.4 , 3.6, 3.7, 3.8, 3.9, 3.10, 3.11 versions, probably everything that is possible is installed with ++. Dear developer, take your project and stick it up your ass up to your elbow and never stick it out.

**Comment by mrh0wl** [comment]
![image](https://user-images.githubusercontent.com/32224733/202946523-13315af5-35e8-494d-a8a3-b519e2375869.png)

I reinstalled python and downloaded Cloudmare again and it worked fine, and I asked a friend to install it on his machine and it also worked. So it's an issue with your machine.

**Comment by jamfea** [comment]
> After spending more than five hours, I still haven't installed the lxml library. I don’t know how this is possible, I searched for an answer on Google, reinstalled python 3.4 , 3.6, 3.7, 3.8, 3.9, 3.10, 3.11 versions, probably everything that is possible is installed with ++. Dear developer, take your project and stick it up your ass up to your elbow and never stick it out.

Works fine on my machine just fine as well. Your comment is just out right rude and you shouldn't be appreciated the project is open source in the first place. Have some respect.
