### ISSUE TITLE
problem [!]WARNING: Virustotal API key not found!

### ISSUE THREAD

**Issue by jesussuarz** [mrh0wl/Cloudmare#45]
hello

I get the following error when running the tool:

`[*]PROCESS: Enumerating subdomains now for target.com
[!]WARNING: Virustotal API key not found! Do you want to enter your API key?:  [y/N]EOF when reading a line
Process Virustotal-9:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/scripts/Cloudmare/lib/tools/sublist3r.py", line 260, in run
    domain_list = self.enumerate()
  File "/scripts/Cloudmare/lib/tools/sublist3r.py", line 738, in enumerate
    resp = json.loads(resp)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int
[*]PROCESS: Enumerating misconfigured subdomains
   [!]WARNING: Total Misconfigured Subdomains Found: 0
      [-]ERROR: misconfigured subdomains not found
[*]PROCESS: Bruteforcing domain extensions and getting DNS records`

how can I solve that?

**Comment by jamfea** [comment]
You will need to sign up for a VirusTotal account and generate an API Key 

https://www.virustotal.com/gui/join-us

**Comment by fkoars** [comment]
You can put API key here
`/Cloudmare/data/APIs/api.conf`

**Comment by mrh0wl** [comment]
As I see, there's a problem using the sublist3r tool (a third-party tool that I use for scan subdomains) in Linux, but I can't handle tests for Linux OS for now. So the best option it's what was mentioned by the last two users. 

Also, I highly recommend that if sublist3r can't search for active or misconfigured subdomains, use Censys or SecurityTrail APIs instead to perform a deep search (don't forget to use --disable-sublister flag to avoid sublist3r search).
