### ISSUE TITLE
Six Moves Issue on Windows?

### ISSUE THREAD

**Issue by Spectre0918** [mrh0wl/Cloudmare#58]
[!]WARNING: thirdparty.urllib3.packages.six.moves module is required. Do you want to install? [Y/n]Y
ERROR: Could not find a version that satisfies the requirement thirdparty.urllib3.packages.six.moves (from versions: none)
ERROR: No matching distribution found for thirdparty.urllib3.packages.six.moves
      [-]ERROR: thirdparty.urllib3.packages.six.moves module is not installed! Try to install it manually.
[!]WARNING: thirdparty.urllib3.packages.six.moves module is required. Do you want to install? [Y/n]Y

**Comment by TheSulak3** [comment]
uninstall python 3.12 and install 3.11, there u go, then instal urllib3 manually with this command "pip install urllib3" without quotes

**Comment by Spectre0918** [comment]
Thanks
