### ISSUE TITLE
Questions on misconfiguration and how Cloudmare works

### ISSUE THREAD

**Issue by Ryzeros** [MrH0wl/Cloudmare#9]
Hi MrH0wl,

I am trying to get some information on the common misconfigurations and how Cloudmare works. However, I was unable to find your contact information. Would you be able to provide me with some information on it? Thanks.

**Comment by MrH0wl** [comment]
Hi,

You can contact me here: https://twitter.com/SecMare

I've been busy at work these days, so I haven't had time to respond, I'm sorry.
